### ISSUE TITLE
KeyError: 'chapters'

### ISSUE THREAD

**Issue by Pfurr** [AlexPerathoner/YT-Chapters-Downloader#2]
Ciao Alex, sto testando il tuo script, e mi ritorna questo errore:

`Fetching video info...
Finding best quality...
Found video: 1080p@25
Found audio: 160kbps
Downloading video...
Downloading audio...
Resolving chapters
Traceback (most recent call last):
  File "/.../youtubeChaptersDownloader.py", line 77, in <module>
    if(j['chapters'] == None):
KeyError: 'chapters'`

**Comment by AlexPerathoner** [comment]
Ciao, potresti inviarmi il link del video con cui lo stai usando?

**Comment by Pfurr** [comment]
Ho testato più di un link. L'ultimo che ho testato è questo: https://www.youtube.com/watch?v=pvkTC2xIbeY e ritorna un nuovo errore:

Fetching video info...
Finding best quality...
Found video: 1080p@25
Found audio: 160kbps
Downloading video...
Downloading audio...
Resolving chapters
Traceback (most recent call last):
  File "/.../youtubeChaptersDownloader.py", line 94, in <module>
    print("Found " + len(chapters) + " chapters")

TypeError: can only concatenate str (not "int") to str

Ps: Lo script sta girando su osx.

**Comment by AlexPerathoner** [comment]
Ho appena caricato una nuova versione, dovrebbe risolvere il problema. Fammi sapere se funziona

**Comment by Pfurr** [comment]
al momento ho risolto in un altro modo! Avendo disinstallato le dipendenze non posso testarlo. Grazie lo stesso, ad ogni modo. Ps: Se lo hai testato e fixato, dovrebbe funzionare, e altri utenti potrebbe beneficiarne.
